---
apiVersion: v1
kind: Service
metadata:
  name: load-tester
  namespace: namespace_filler
  labels:
    app: joel
spec:
  ports:
    - port: 80
      name: load-tester
  clusterIP: None
  selector:
    app: joel
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: load-tester
  namespace: namespace_filler
spec:
  selector:
    matchLabels:
      app: joel # has to match .spec.template.metadata.labels
  serviceName: "load-tester"
  replicas: num_replicas
  template:
    #nodeSelector:
      #managed-search/instance-type: n1-standard-2
    metadata:
      labels:
        app: joel # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: load-tester
          image: sarkaramrit2/joel_load_tester:latest
          ports:
            - containerPort: 80
              name: load-tester