---
apiVersion: v1
kind: Service
metadata:
  name: loader
  namespace: namespace_filler
  labels:
    app: joel
spec:
  ports:
    - port: 80
      name: loader
  clusterIP: None
  selector:
    app: joel
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loader
  namespace: namespace_filler
spec:
  nodeSelector:
    managed-search/instance-type: n1-standard-2
  selector:
    matchLabels:
      app: joel # has to match .spec.template.metadata.labels
  serviceName: "loader"
  replicas: num-replicas
  template:
    metadata:
      labels:
        app: joel # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: loader
          image: sarkaramrit2/joel_loader:latest
          ports:
            - containerPort: 80
              name: loader